const WASM = Uint8Array.from(atob("AGFzbQEAAAABZg1gAX8Bf2ACf38Bf2ADf39/AGACf38AYAAAYAF/AGAEf39/fwBgBX9/f39/AX9gA39/fgBgA39/fwF/YAABf2AVf39/f39/f39/f39/f39/f39/f39/AX9gCn9/f39/f39/f38BfwINAQNlbnYFYWJvcnQABgM4NwIBAAEEAAIFAQEAAQACAAMDAAUFAAcCAQABAAQIBAMDAgAFAwUBCQYDBAEKAQMCAAQLDAAEAQIFAwEAAQZKDn8BQcAIC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQaygAgsHQggFX2dHcnkANAVfa3VlegAxBV8wU0dMADcFXzR2THUANgVfaVVlTQAzBV9rR3R3ADIFX2FMMHMANQZtZW1vcnkCAAgBKgwBNwrOWzdNACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCE8EQEGgC0GgHkGyAUEtEAAACyMNIAA2AgAgACgCBCABaiACOgAAIw1BBGokDQtLACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCE8EQEGgC0GgHkGnAUEtEAAACyMNIAA2AgAgACgCBCABai0AACMNQQRqJA0LJQAjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIIIw1BBGokDQtDACMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAAQGSABTQRAQaALQaAfQc4AQSkQAAALIAAgAUECdGooAgAjDUEEaiQNCxoAIw1BrCBIBEBBwKACQfCgAkEBQQEQAAALCz4BAX8jDUEIayQNEAUjDUIANwMAIw1BDEEEEAwiATYCACMNIAE2AgQjDSABIAAQLSIANgIAIw1BCGokDSAAC0wAIw1BBGskDRAFIw1BADYCACMNIAA2AgAgABAZIAFNBEBBoAtBoB9B3QBBKRAAAAsjDSAANgIAIAAgAUECdGogAjYCACMNQQRqJA0LIwAgAEUEQA8LIABBFGsiABANIwhGBEAgABATIwRBAWokBAsLUQECfyMNQQhrJA0QBSMNQgA3AwAjDSABEAYiAzYCAANAIAEgAkoEQCMNIAM2AgQgAyACIAAgAmotAAAQASACQQFqIQIMAQsLIw1BCGokDSADC0sAIw1BBGskDRAFIw1BADYCACMNIAA2AgAgASAAKAIMTwRAQaALQdAdQfIAQSoQAAALIw0gADYCACAAKAIEIAFqLQAAIw1BBGokDQsKACAAKAIEQXxxC6MBAQF/IABB7P///wNPBEBB4AlBoApBhQJBHxAAAAsjASMCTwRAAkBBgBAhAgNAIAIQLGshAiMDRQRAIwFBAXRBgAhqJAIMAgsgAkEASg0ACyMBIwEjAmtBgAhJQQp0aiQCCwsjCkUEQBAcCyMKIABBEGoQKyICIAE2AgwgAiAANgIQIAIjCSMIECEgAhAiIwFqJAEgAkEUaiIBQQAgAPwLACABCwoAIAAoAgRBA3ELSAEBfyABRQRADwsgAUEUayIBEA0jCEYEQCAAQRRrIgAQDSIDIwhFRgRAIAAgASACGxATBSMDQQFGIANBA0ZxBEAgARATCwsLC0QAIw1BBGskDRAFIw1BADYCACAAQf////8ASwRAQfAIQaAfQTNBPBAAAAsjDSAAQQJ0QQkQDCIANgIAIw1BBGokDSAAC8MBAQR/IAEoAgBBfHEiA0GAAkkEfyADQQR2BUEfQfz///8DIAMgA0H8////A08bIgNnayIEQQdrIQIgAyAEQQRrdkEQcwshBCABKAIIIQUgASgCBCIDBEAgAyAFNgIICyAFBEAgBSADNgIECyABIAAgAkEEdCAEakECdGoiASgCYEYEQCABIAU2AmAgBUUEQCAAIAJBAnRqIgEoAgRBfiAEd3EhAyABIAM2AgQgA0UEQCAAIAAoAgBBfiACd3E2AgALCwsLvAIBBX8gASgCACEDIAFBBGogASgCAEF8cWoiBCgCACICQQFxBEAgACAEEBAgASADQQRqIAJBfHFqIgM2AgAgAUEEaiABKAIAQXxxaiIEKAIAIQILIANBAnEEQCABQQRrKAIAIgEoAgAhBiAAIAEQECABIAZBBGogA0F8cWoiAzYCAAsgBCACQQJyNgIAIARBBGsgATYCACAAIANBfHEiAkGAAkkEfyACQQR2BUEfQfz///8DIAIgAkH8////A08bIgJnayIDQQdrIQUgAiADQQRrdkEQcwsiAiAFQQR0akECdGooAmAhAyABQQA2AgQgASADNgIIIAMEQCADIAE2AgQLIAAgBUEEdCACakECdGogATYCYCAAIAAoAgBBASAFdHI2AgAgACAFQQJ0aiIAIAAoAgRBASACdHI2AgQLEgAgACAANgIEIAAgADYCCCAAC4YBAQJ/IAAjBkYEQCAAKAIIJAYLAkAgABALIgFFBEAgACgCCBoMAQsgASAAKAIIIgI2AgggAiABEB8LIwchASAAKAIMIgJBAk0Ef0EBBSACQYAgKAIASwRAQaALQeALQRVBHBAAAAsgAkECdEGEIGooAgBBIHELIQIgACABIwhFQQIgAhsQIQvSAQEDfwJAAkACQAJAAkACQAJAAkACQCAAQQhrKAIADgoAAQIDBAUICAgGBwsPCw8LDwsgABAjDwsgABAjDwsjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIEIQEjDSAANgIAIAEgACgCDEECdGohAgNAIAEgAkkEQCABKAIAIgMEQCADEAgLIAFBBGohAQwBCwsjDSAANgIAIAAoAgAQCCMNQQRqJA0PCw8LAAsjDUEEayQNEAUjDUEANgIAIw0gADYCACAAKAIAEAgjDUEEaiQNC5UFAgZ/AX4jDUEUayQNEAUjDUEAQRT8CwAjDUEIEA8iATYCACMNIAE2AgQgAUEAQefMp9AGEAcjDSABNgIEIAFBAUGF3Z7bexAHIw0gATYCBCABQQJB8ua74wMQByMNIAE2AgQgAUEDQbrqv6p6EAcjDSABNgIEIAFBBEH/pLmIBRAHIw0gATYCBCABQQVBjNGV2HkQByMNIAE2AgQgAUEGQauzj/wBEAcjDSABNgIEIAFBB0GZmoPfBRAHIw0gADYCBCAAEAOsQgOGIQcjDSAANgIEIAAQA0HAAG9BOEgEfyMNIAA2AgRBwAAgABADQcAAb2sFIw0gADYCBEGAASAAEANBwABvawshBiMNIAA2AgQjDSAAEAMgBmoQBiIGNgIIA0AjDSAANgIEIAAQAyADSgRAIw0gBjYCBCMNIAA2AgwgBiADIAAgAxACEAEgA0EBaiEDDAELCyMNIAY2AgQjDSAANgIMIAYgABADQYABEAEDQCAEQQhIBEAjDSAGNgIEIw0gBjYCDCAGIAYQA0EBayAEayAHIARBA3SsiKdB/wFxEAEgBEEBaiEEDAELCwNAIw0gBjYCBCAGEAMgBUoEQCMNIAE2AgQjDSAGNgIMIAEgBiAFEC8gBUFAayEFDAELCyMNQSAQBiIANgIQA0AgAkEISARAIw0gADYCBCMNIAE2AgwgACACQQJ0IgMgASACEARBGHYQASMNIAA2AgQjDSABNgIMIAAgA0EBaiABIAIQBEEQdkH/AXEQASMNIAA2AgQjDSABNgIMIAAgA0ECaiABIAIQBEEIdkH/AXEQASMNIAA2AgQjDSABNgIMIAAgA0EDaiABIAIQBEH/AXEQASACQQFqIQIMAQsLIw1BFGokDSAAC9cHAgt/A34jDUE8ayQNEAUjDUEAQTz8CwAjDSABNgIAAkACQCABEANBDEcNACMNIAM2AgAgAxADQRBHDQAjDSAANgIAIw0gABAwIgg2AgQjDUEQEAYiADYCCCMNQRAQBiIONgIMIw0gCDYCACMNIAA2AhAjDSAONgIUIAggACAOEBcjDUEQEAYiDzYCGANAIAVBDEgEQCMNIA82AgAjDSABNgIQIA8gBSABIAUQAhABIAVBAWohBQwBCwsjDSAPNgIAIA9BD0EBEAEjDUEQEAYiADYCHCMNIAA2AgAjDSAONgIQIw0gBDYCFCMNIAQ2AiAgACAOIAQgBBADECgjDSAANgIAIw0gDjYCECMNIAI2AhQjDSACNgIgIAAgDiACIAIQAxAoIw1BEBAGIgE2AiQjDSAENgIAIAQQA6xCA4YhECMNIAI2AgAgAhADrEIDhiERA0AgCUEISARAIw0gATYCACABQQcgCWsgECAJQQN0rCISiKdB/wFxEAEjDSABNgIAIAFBDyAJayARIBKIp0H/AXEQASAJQQFqIQkMAQsLA0AgCkEQSARAIw0gADYCACMNIAA2AhAgACAKEAIhBCMNIAE2AhAgACAKIAEgChACIARzEAEgCkEBaiEKDAELCyMNIAA2AgAjDSAONgIQIAAgDhApIw1BEBAGIgE2AigjDSAINgIAIw0gDzYCECMNIAE2AhQgCCAPIAEQFyMNQRAQBiIENgIsA0AgC0EQSARAIw0gBDYCACMNIAA2AhAgACALEAIhBSMNIAE2AhAgBCALIAEgCxACIAVzQf8BcRABIAtBAWohCwwBCwsDQCAGQRBIBEAjDSAENgIAIAQgBhACIQAjDSADNgIAIAcgAyAGEAIgAHNyIQcgBkEBaiEGDAELCyAHQf8BcQ0AIw0gAjYCACMNIAIQAxAGIgA2AjAjDUEQEAYiAzYCNANAIA1BEEgEQCMNIAM2AgAjDSAPNgIQIAMgDSAPIA0QAhABIA1BAWohDQwBCwsjDSADNgIAIAMQJSMNQRAQBiIENgI4A0AjDSACNgIAIAIQAyAMSgRAIw0gCDYCACMNIAM2AhAjDSAENgIUIAggAyAEEBcjDSACNgIAIAIQAyAMa0EQTgR/QRAFIw0gAjYCACACEAMgDGsLIQVBACEBA0AgASAFSARAIw0gADYCACMNIAI2AhAgAiABIAxqIgYQAiEHIw0gBDYCECAAIAYgBCABEAIgB3NB/wFxEAEgAUEBaiEBDAELCyAMQRBqIQwjDSADNgIAIAMQJQwBCwsMAQtBACEACyMNQTxqJA0gAAviCQEMfyMNQRBrJA0QBSMNQgA3AwAjDUIANwMIIw1BEBAGIgM2AgADQCAEQRBIBEAjDSADNgIEIw0gATYCCCADIAQgASAEEAIQASAEQQFqIQQMAQsLQQAhAQNAIAFBBEgEQCMNIAA2AgQgACABEAQhBCMNIAM2AgQjDSADNgIIIAMgAUECdCIFIAMgBRACIARBGHZzEAEjDSADNgIEIw0gAzYCCCADIAVBAWoiBiADIAYQAiAEQRB2cxABIw0gAzYCBCMNIAM2AgggAyAFQQJqIgYgAyAGEAIgBEEIdnMQASMNIAM2AgQjDSADNgIIIAMgBUEDaiIFIAMgBRACIARzEAEgAUEBaiEBDAELC0EBIQQDQCAEQQ5MBEBBACEBA0AgAUEQSARAIw0gAzYCBCMNQdAcNgIIIw0gAzYCDCADIAFB0BwgAyABEAIQChABIAFBAWohAQwBCwsjDSADNgIEIANBARACIQEjDSADNgIEIw0gAzYCCCADQQEgA0EFEAIQASMNIAM2AgQjDSADNgIIIANBBSADQQkQAhABIw0gAzYCBCMNIAM2AgggA0EJIANBDRACEAEjDSADNgIEIANBDSABEAEjDSADNgIEIANBAhACIQEjDSADNgIEIANBBhACIQUjDSADNgIEIw0gAzYCCCADQQIgA0EKEAIQASMNIAM2AgQjDSADNgIIIANBBiADQQ4QAhABIw0gAzYCBCADQQogARABIw0gAzYCBCADQQ4gBRABIw0gAzYCBCADQQ8QAiEBIw0gAzYCBCMNIAM2AgggA0EPIANBCxACEAEjDSADNgIEIw0gAzYCCCADQQsgA0EHEAIQASMNIAM2AgQjDSADNgIIIANBByADQQMQAhABIw0gAzYCBCADQQMgARABIARBDkgEQEEAIQEDQCABQQRIBEAjDSADNgIEIAMgAUECdCIIEAIhCyMNIAM2AgQgAyAIQQFqIgUQAiEMIw0gAzYCBCADIAhBAmoiBhACIQkjDSADNgIEIAMgCEEDaiIHEAIiCiALIAxzIg0gCXNzIQ4jDSADNgIEIAMgCCANQf8BcUEHdkEbbCANQQF0c0H/AXEgCyAOc3NB/wFxEAEjDSADNgIEIAMgBSAJIAxzIgVB/wFxQQd2QRtsIAVBAXRzQf8BcSAMIA5zc0H/AXEQASMNIAM2AgQgAyAGIAkgCnMiBUH/AXFBB3ZBG2wgBUEBdHNB/wFxIAkgDnNzQf8BcRABIw0gAzYCBCADIAcgCiALcyIFQf8BcUEHdkEbbCAFQQF0c0H/AXEgCiAOc3NB/wFxEAEgAUEBaiEBDAELCwtBACEBA0AgAUEESARAIw0gADYCBCAAIARBAnQgAWoQBCEFIw0gAzYCBCMNIAM2AgggAyABQQJ0IgYgAyAGEAIgBUEYdnMQASMNIAM2AgQjDSADNgIIIAMgBkEBaiIHIAMgBxACIAVBEHZzEAEjDSADNgIEIw0gAzYCCCADIAZBAmoiByADIAcQAiAFQQh2cxABIw0gAzYCBCMNIAM2AgggAyAGQQNqIgYgAyAGEAIgBXMQASABQQFqIQEMAQsLIARBAWohBAwBCwtBACEAA0AgAEEQSARAIw0gAjYCBCMNIAM2AgggAiAAIAMgABACEAEgAEEBaiEADAELCyMNQRBqJA0LPwAjDUEEayQNEAUjDUEANgIAIw0gADYCACABIABBFGsoAhBBAXZPBH9BfwUgACABQQF0ai8BAAsjDUEEaiQNCw0AIABBFGsoAhBBAnYLjgEBAn8gAUGAAkkEfyABQQR2BUEfIAEQGyIBZ2siA0EHayECIAEgA0EEa3ZBEHMLIQEgACACQQJ0aigCBEF/IAF0cSIBBH8gACABaCACQQR0akECdGooAmAFIAAoAgBBfyACQQFqdHEiAQR/IAAgACABaCIAQQJ0aigCBGggAEEEdGpBAnRqKAJgBUEACwsLHQAgAEEBQRsgAGdrdGpBAWsgACAAQf7///8BSRsLlwEBAn8/ACIAQQBMBH9BASAAa0AAQQBIBUEACwRAAAtBsKACQQA2AgBB0KwCQQA2AgADQCABQRdJBEAgAUECdEGwoAJqQQA2AgRBACEAA0AgAEEQSQRAIAFBBHQgAGpBAnRBsKACakEANgJgIABBAWohAAwBCwsgAUEBaiEBDAELC0GwoAJB1KwCPwCsQhCGEB1BsKACJAoLhgEBA38gAUETakFwcUEEayEBIAAoAqAMIgMEQCABQRBrIgUgA0YEQCADKAIAIQQgBSEBCwsgAqdBcHEgAWsiA0EUSQRADwsgASAEQQJxIANBCGsiA0EBcnI2AgAgAUEANgIEIAFBADYCCCABQQRqIANqIgNBAjYCACAAIAM2AqAMIAAgARARC24BAn8jACIABEAgABAICyMLIgAEQCAAEAgLQZAREAhB4BIQCEGwFxAIQYAaEAhB0BwQCEGgHRAIQaALEAhB8AgQCEHgCRAIIwUiARALIQADQCAAIAFHBEAgABANGiAAQRRqEBQgABALIQAMAQsLCxIAIAAgASAAKAIEQQNxcjYCBAsSACAAIAAoAgRBfHEgAXI2AgQLKQEBfyABKAIIIQMgACABIAJyNgIEIAAgAzYCCCADIAAQHyABIAA2AggLDQAgACgCAEF8cUEEagsJACAAKAIAEAgLEQAgACABNgIAIAAgAUEAEA4LZgEBfyMNQQhrJA0QBSMNQgA3AwBBDyEBA0AgAUEMTgRAAkAjDSAANgIAIw0gADYCBCAAIAEgACABEAJBAWpB/wFxEAEjDSAANgIAIAAgARACDQAgAUEBayEBDAILCwsjDUEIaiQNC9wEAQd/Iw1BJGskDRAFIw1BAEEk/AsAIw0gADYCACMNIAA2AgQgABADQcAASgRAIw0gADYCBCMNIAAQFSIANgIACyMNQcAAEAYiCDYCCANAIw0gADYCBCAAEAMgAkoEQCMNIAg2AgQjDSAANgIMIAggAiAAIAIQAhABIAJBAWohAgwBCwsjDUHAABAGIgA2AhAjDUHAABAGIgI2AhQDQCADQcAASARAIw0gADYCBCMNIAg2AgwgACADIAggAxACQdwAc0H/AXEQASMNIAI2AgQjDSAINgIMIAIgAyAIIAMQAkE2c0H/AXEQASADQQFqIQMMAQsLIw0gAjYCBCMNIAIQAyEIIw0gATYCBCABEAMgCGoQBiIDNgIYA0AjDSACNgIEIAIQAyAESgRAIw0gAzYCBCMNIAI2AgwgAyAEIAIgBBACEAEgBEEBaiEEDAELCwNAIw0gATYCBCABEAMgBUoEQCMNIAM2AgQjDSACNgIMIAIQAyAFaiEEIw0gATYCDCADIAQgASAFEAIQASAFQQFqIQUMAQsLIw0gAzYCBCMNIAMQFSIBNgIcIw0gADYCBCMNIAAQAyEDIw0gATYCBCABEAMgA2oQBiICNgIgA0AjDSAANgIEIAAQAyAGSgRAIw0gAjYCBCMNIAA2AgwgAiAGIAAgBhACEAEgBkEBaiEGDAELCwNAIw0gATYCBCABEAMgB0oEQCMNIAI2AgQjDSAANgIMIAAQAyAHaiEDIw0gATYCDCACIAMgASAHEAIQASAHQQFqIQcMAQsLIw0gAjYCBCACEBUjDUEkaiQNC6IDAQZ/Iw1BGGskDRAFIw1BAEEY/AsAIw0gATYCACMNIAA2AgQjDSABIAAQJiIGNgIIIw1BIBAGIgQ2AgwjDUEAEAYiADYCEEEBIQUDQCADQSBIBEAjDSAANgIAIw0gABADIQcjDSACNgIAIAIQAyAHakEBahAGIgc2AhRBACEBA0AjDSAANgIAIAAQAyABSgRAIw0gBzYCACMNIAA2AgQgByABIAAgARACEAEgAUEBaiEBDAELC0EAIQEDQCMNIAI2AgAgAhADIAFKBEAjDSAHNgIAIw0gADYCBCAAEAMgAWohCCMNIAI2AgQgByAIIAIgARACEAEgAUEBaiEBDAELCyMNIAc2AgAjDSAHNgIEIAcgBxADQQFrIAVB/wFxEAEjDSAGNgIAIw0gBzYCBCMNIAYgBxAmIgA2AhAjDSAANgIAIAAQA7dBICADa7ek/AIhB0EAIQEDQCABIAdIBEAjDSAENgIAIw0gADYCBCAEIAEgA2ogACABEAIQASABQQFqIQEMAQsLIAMgB2ohAyAFQQFqIQUMAQsLIw1BGGokDSAEC5sBAQR/Iw1BCGskDRAFIw1CADcDAANAIAMgBUoEQEEQIAMgBWsiBCAEQRBOGyEGQQAhBANAIAQgBkgEQCMNIAA2AgAjDSAANgIEIAAgBBACIQcjDSACNgIEIAAgBCACIAQgBWoQAiAHcxABIARBAWohBAwBCwsjDSAANgIAIw0gATYCBCAAIAEQKSAFQRBqIQUMAQsLIw1BCGokDQuHAwEHfyMNQRBrJA0QBSMNQgA3AwAjDUIANwMIIw1BEBAGIgc2AgAjDUEQEAYiCDYCBANAIAJBEEgEQCMNIAg2AggjDSAANgIMIAggAiAAIAIQAhABIAJBAWohAgwBCwsDQCAFQYABSARAIw0gATYCCCABIAVBA3YQAkEHIAVBB3FrQQdxdkEBcQRAQQAhAgNAIAJBEEgEQCMNIAc2AggjDSAHNgIMIAcgAhACIQMjDSAINgIMIAcgAiAIIAIQAiADcxABIAJBAWohAgwBCwsLQQAhAkEAIQYDQCAGQRBIBEAjDSAINgIIIAggBhACQQFxIw0gCDYCCCMNIAg2AgwgCCAGIAJBB3QgCCAGEAJBAXZyQf8BcRABIQIgBkEBaiEGDAELCyACBEAjDSAINgIIIw0gCDYCDCAIQQAgCEEAEAJB4QFzEAELIAVBAWohBQwBCwsDQCAEQRBIBEAjDSAANgIIIw0gBzYCDCAAIAQgByAEEAIQASAEQQFqIQQMAQsLIw1BEGokDQssAD8AQRB0QaygAmtBAXYkAkHQChASJAVB8AoQEiQHQYAMEBIkCUEAEAYkCwuTAgEDfyABQfz///8DSwRAQeAJQbAMQc0DQR0QAAALIABBDCABQRNqQXBxQQRrIAFBDE0bIgMQGiIBRQRAQQQgACgCoAw/ACIBQRB0QQRrR3QgAxAbIAMgA0GAAk8bakH//wNqQYCAfHFBEHYhAiABIAIgASACShtAAEEASARAIAJAAEEASARAAAsLIAAgAUEQdD8ArEIQhhAdIAAgAxAaIQELIAEoAgAaIAAgARAQIAEoAgAiAkF8cSADayIEQRBPBEAgASADIAJBAnFyNgIAIAFBBGogA2oiAiAEQQRrQQFyNgIAIAAgAhARBSABIAJBfnE2AgAgAUEEaiABKAIAQXxxaiIAIAAoAgBBfXE2AgALIAEL/wIBAn8CQAJAAkACQCMDDgMAAQIDC0EBJANBACQEEB4jByQGIwQPCyMIRSEBIwYQCyEAA0AgACMHRwRAIAAkBiAAEA0gAUcEQCAAIAEQIEEAJAQgAEEUahAUIwQPCyAAEAshAAwBCwtBACQEEB4jBhALIwdGBEAjDSEAA0AgAEGsoAJJBEAgACgCABAIIABBBGohAAwBCwsjBhALIQADQCAAIwdHBEAgABANIAFHBEAgACABECAgAEEUahAUCyAAEAshAAwBCwsjCSEAIwckCSAAJAcgASQIIAAQCyQGQQIkAwsjBA8LIwYiACMHRwRAIAAQCyQGIAAQDRogAEGsoAJJBEAgAEEANgIEIABBADYCCAUjASAAECJrJAEgAEEEaiIAQaygAk8EQCMKRQRAEBwLIABBBGshASAAQQ9xQQEgABsEf0EBBSABKAIAQQFxCxogASABKAIAQQFyNgIAIwogARARCwtBCg8LIwcjBzYCBCMHIwc2AghBACQDC0EAC7YBAQF/Iw1BEGskDRAFIw1CADcDACMNQgA3AwggAEUEQCMNQQxBAxAMIgA2AgALIw0gADYCBCAAQQAQJCMNIAA2AgQgAEEANgIEIw0gADYCBCAAQQA2AgggAUH8////A0sEQEHwCEGgCUETQTkQAAALIw0gAUEBEAwiAjYCCCMNIAA2AgQjDSACNgIMIAAgAhAkIw0gADYCBCAAIAI2AgQjDSAANgIEIAAgATYCCCMNQRBqJA0gAAvwAQEDfyMNQQRrJA0QBSMNQQA2AgAjDSAANgIAIAEgACgCCCICQQJ2SwRAIAFB/////wBLBEBB8AhB0B1BE0EwEAAACyMNIAA2AgACQEH8////AyACQQF0IgIgAkH8////A08bIgJBCCABIAFBCE0bQQJ0IgEgASACSRsiAyAAKAIAIgJBFGsiBCgCAEF8cUEQa00EQCAEIAM2AhAgAiEBDAELIAMgBCgCDBAMIgEgAiADIAQoAhAiBCADIARJG/wKAAALIAEgAkcEQCAAIAE2AgAgACABNgIEIAAgAUEAEA4LIAAgAzYCCAsjDUEEaiQNC/8HAQp/Iw1BDGskDRAFIw1CADcDACMNQQA2AggjDUHAABAPIgw2AgADQCAEQRBIBEAjDSAMNgIEIw0gATYCCCABIAIgBEECdGoiBRACQRh0Iw0gATYCCCABIAVBAWoQAkEQdHIjDSABNgIIIAEgBUECahACQQh0ciEDIw0gATYCCCAMIAQgASAFQQNqEAIgA3IQByAEQQFqIQQMAQsLQRAhBANAIARBwABIBEAjDSAMNgIEIAwgBEEPayIDEAQhAiMNIAw2AgQgDCADEAQhASMNIAw2AgQgAkEZdCACQQd2ciABQQ50IAFBEnZycyAMIAMQBEEDdnMhBSMNIAw2AgQgDCAEQQJrIgMQBCECIw0gDDYCBCAMIAMQBCEBIw0gDDYCBCACQQ90IAJBEXZyIAFBDXQgAUETdnJzIAwgAxAEQQp2cyECIw0gDDYCBCMNIAw2AgggDCAEQRBrEAQgBWohASMNIAw2AgggDCAEIAwgBEEHaxAEIAFqIAJqEAcgBEEBaiEEDAELCyMNIAA2AgQgAEEAEAQhCCMNIAA2AgQgAEEBEAQhBCMNIAA2AgQgAEECEAQhAyMNIAA2AgQgAEEDEAQhBiMNIAA2AgQgAEEEEAQhByMNIAA2AgQgAEEFEAQhAiMNIAA2AgQgAEEGEAQhASMNIAA2AgQgAEEHEAQhBQNAIAtBwABIBEAjDUGAGjYCBCMNQQRrJA0QBSMNQQA2AgAjDUGAGjYCACALQYwaKAIATwRAQaALQdAdQfIAQSoQAAALIw1BgBo2AgBBhBooAgAgC0ECdGooAgAhCSMNQQRqJA0jDSAMNgIEIAwgCxAEIAdBB3QgB0EZdnIgB0EadCAHQQZ2ciAHQRV0IAdBC3Zyc3MgBWogAiAHcSAHQX9zIAFxc2ogCWpqIQogCEEKdCAIQRZ2ciAIQR50IAhBAnZyIAhBE3QgCEENdnJzcyADIARxIAQgCHEgAyAIcXNzaiABIQUgAiEBIAchAiAGIApqIQcgAyEGIAQhAyAIIQQgCmohCCALQQFqIQsMAQsLIw0gADYCBCMNIAA2AgggAEEAIABBABAEIAhqEAcjDSAANgIEIw0gADYCCCAAQQEgAEEBEAQgBGoQByMNIAA2AgQjDSAANgIIIABBAiAAQQIQBCADahAHIw0gADYCBCMNIAA2AgggAEEDIABBAxAEIAZqEAcjDSAANgIEIw0gADYCCCAAQQQgAEEEEAQgB2oQByMNIAA2AgQjDSAANgIIIABBBSAAQQUQBCACahAHIw0gADYCBCMNIAA2AgggAEEGIABBBhAEIAFqEAcjDSAANgIEIw0gADYCCCAAQQcgAEEHEAQgBWoQByMNQQxqJA0L6AMBBH8jDUEMayQNEAUjDUIANwMAIw1BADYCCCMNQTwQDyICNgIAA0AgAUEISARAIw0gAjYCBCMNIAA2AgggACABQQJ0IgMQAkEYdCMNIAA2AgggACADQQFqEAJBEHRyIw0gADYCCCAAIANBAmoQAkEIdHIhBCMNIAA2AgggAiABIAAgA0EDahACIARyEAcgAUEBaiEBDAELC0EIIQADQCAAQTxIBEAjDSACNgIEIAIgAEEBaxAEIQEgAEEHcQR/IABBCG9BBEYEfyMNQdAcNgIEQdAcIAFBGHYQCkEYdCMNQdAcNgIEQdAcIAFBEHZB/wFxEApBEHRyIw1B0Bw2AgRB0BwgAUEIdkH/AXEQCkEIdHIhAyMNQdAcNgIEQdAcIAFB/wFxEAogA3IFIAELBSMNQdAcNgIEQdAcIAFBCHQgAUEYdnIiAUEYdhAKQRh0Iw1B0Bw2AgRB0BwgAUEQdkH/AXEQCkEQdHIjDUHQHDYCBEHQHCABQQh2Qf8BcRAKQQh0ciEDIw1B0Bw2AgRB0BwgAUH/AXEQCiADciMNQaAdNgIEQaAdIABBCG0QCkEYdHMLIQEjDSACNgIEIw0gAjYCCCACIAAgAiAAQQhrEAQgAXMQByAAQQFqIQAMAQsLIw1BDGokDSACC2EBAn8jDUEEayQNEAUjDUEANgIAIw1BAEEBEAwiAEGAHkEA/AoAACAANgIAQRBBBRAMIgEgADYCACABIABBABAOIAEgADYCBCABQQA2AgggAUEANgIMIw1BBGokDSABJAALmwYBCH8jDUHYAGskDRAFIw1BAEHYAPwLAAJ/AkAjDEUNACMNIAAgARAJIgE2AgAjDSACIAMQCSICNgIEIw0gBCAFEAkiAzYCCCMNIAYgBxAJIgQ2AgwjDSAIIAkQCSIFNgIQIw0gCiALEAkiBjYCFCMNIAwgDRAJIgc2AhgjDSAOIA8QCSIINgIcIw0gECAREAkiCTYCICMNIBIgExAJIgo2AiQjDSABNgIoIw0gARADIQsjDSACNgIoIAIQAyALaiELIw0gAzYCKCADEAMgC2oQBiILNgIsA0AjDSABNgIoIAEQAyAYSgRAIw0gCzYCKCAVIgBBAWohFSMNIAE2AjAgCyAAIAEgGBACEAEgGEEBaiEYDAELCwNAIw0gAjYCKCACEAMgGUoEQCMNIAs2AiggFSIAQQFqIRUjDSACNgIwIAsgACACIBkQAhABIBlBAWohGQwBCwsDQCMNIAM2AiggAxADIBpKBEAjDSALNgIoIBUiAEEBaiEVIw0gAzYCMCALIAAgAyAaEAIQASAaQQFqIRoMAQsLIw1BDhAGIgA2AjQDQCAWQQ5IBEAjDSAANgIoIAAgFkHgHyAWEBhB/wFxEAEgFkEBaiEWDAELCyMNIwsiATYCKCMNIAs2AjAjDSAANgI4Iw0gASALIAAQJyIANgI8Iw0gADYCKCMNIAU2AjAjDSAGNgI4Iw0gBzYCQCMNIAQ2AkQjDSAAIAUgBiAHIAQQFiIBNgJIA0AjDSAANgIoIAAQAyAbSgRAIw0gADYCKCAAIBtBABABIBtBAWohGwwBCwsgAUUNACMNIAE2AigjDSAINgIwIw0gCTYCOCMNIAo2AkAjDSAENgJEIw0gASAIIAkgCiAEEBYiADYCTCMNIAE2AlADQCMNIAE2AiggARADIBxKBEAjDSABNgIoIAEgHEEAEAEgHEEBaiEcDAELCyAARQ0AIw0gADYCVANAIw0gADYCKCAAEAMgF0oEQCMNIAA2AiggFCAXaiAAIBcQAjoAACAXQQFqIRcMAQsLIw0gADYCKCAAEAMMAQtBfwsjDUHYAGokDQvPBQAjDUE8ayQNEAUjDUEAQTz8CwAjDSAAIAEQCSIBNgIAIw0gAiADEAkiAjYCBCMNIAQgBRAJIgM2AggjDSAGIAcQCSIFNgIMIw0gCCAJEAkiBjYCECMNQYABEAYiBzYCFEEAIQADQCAAQYABSARAIw0gBzYCGCMNQZARNgIcIw1BsBc2AiAjDUEEayQNEAUjDUEANgIAIw1BsBc2AgAgAEG8FygCAE8EQEGgC0HQHUHyAEEqEAAACyMNQbAXNgIAQbQXKAIAIABBAnRqKAIAIQQjDUEEaiQNQZARIAQQCiEEIw1B4BI2AhwgByAAQeASIAAQCiAEc0H/AXEQASAAQQFqIQAMAQsLIw0gATYCGCMNIAEQAyEEIw0gAjYCGCACEAMgBGoQBiIANgIkQQAhBANAIw0gATYCGCABEAMgBEoEQCMNIAA2AhgjDSABNgIcIAAgBCABIAQQAhABIARBAWohBAwBCwtBACEEA0AjDSACNgIYIAIQAyAESgRAIw0gADYCGCMNIAE2AhwgARADIARqIQgjDSACNgIcIAAgCCACIAQQAhABIARBAWohBAwBCwsjDUEVEAYiBDYCKEEAIQIDQCACQRVIBEAjDSAENgIYIAQgAkHgHiACEBhB/wFxEAEgAkEBaiECDAELCyMNIAc2AhgjDSAANgIcIw0gBDYCICMNIAcgACAEECciADYCLEEAIQIDQCACQYABSARAIw0gBzYCGCAHIAJBABABIAJBAWohAgwBCwsjDSAANgIYIw0gAzYCHCMNIAU2AiAjDSAGNgIwIw0gATYCNCMNIAAgAyAFIAYgARAWIgI2AjhBACEBA0AjDSAANgIYIAAQAyABSgRAIw0gADYCGCAAIAFBABABIAFBAWohAQwBCwsgAkUEQEEAJAwjDUE8aiQNQX8PCyACJAtBASQMIw0jCyIANgIYIAAQAyMNQTxqJA0LpAEBA38jDUEMayQNEAUjDUIANwMAIw1BADYCCCMNIAAQBiIDNgIAIw0jACICNgIEIw0gAzYCCCMNQQRrJA0QBSMNQQA2AgAjDSACNgIAIAIgAigCDCIAQQFqIgEQLiMNIAI2AgAgAigCBCAAQQJ0aiADNgIAIAIgA0EBEA4jDSACNgIAIAIgATYCDCMNQQRqJA0jDSADNgIEIAMoAgQjDUEMaiQNC1UBAn8jDUEEayQNEAUjDUEANgIAA0AjDSMLIgE2AgAgARADIABKBEAjDSMLIgE2AgAgASAAQQAQASAAQQFqIQAMAQsLQQAQBiQLQQAkDCMNQQRqJA0LCgAgACABai0AAAsMACAAIAFqIAI6AAALC78VNwBBjAgLARwAQZgICwEBAEGsCAsBLABBuAgLDgUAAAAQAAAAIAQAACAEAEHcCAsBLABB6AgLIwIAAAAcAAAASQBuAHYAYQBsAGkAZAAgAGwAZQBuAGcAdABoAEGMCQsBPABBmAkLLQIAAAAmAAAAfgBsAGkAYgAvAGEAcgByAGEAeQBiAHUAZgBmAGUAcgAuAHQAcwBBzAkLATwAQdgJCy8CAAAAKAAAAEEAbABsAG8AYwBhAHQAaQBvAG4AIAB0AG8AbwAgAGwAYQByAGcAZQBBjAoLATwAQZgKCycCAAAAIAAAAH4AbABpAGIALwByAHQALwBpAHQAYwBtAHMALgB0AHMAQYwLCwE8AEGYCwsrAgAAACQAAABJAG4AZABlAHgAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQBBzAsLASwAQdgLCxsCAAAAFAAAAH4AbABpAGIALwByAHQALgB0AHMAQZwMCwE8AEGoDAslAgAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABsAHMAZgAuAHQAcwBB3AwLAhwCAEHoDAuIBAEAAAAAAgAA7Jz+YTHXXW16LtFeVZK+WgeDZXuH2u6BUGLGTRXmssICFsxgBPMn3MOhe9g52xl9mFEsziQK3vpLHFBwOO6LLV7fL/3UrW6kbIzTU2fINkTFFsqHyNcLgck04ATNVqmub7dD5qiuReNfXtkkzanwtoTd3hapCDF211Ue9BJSJAHO/1UkYdRmkHlNevMaWiKVT3z22hPb66CO2PXfthPAOexXjjWnemqhcYWOouMDL6Fa1EbW4uKr6AdUEypFncMrB3KLL2HADCWVAE+umJjCr5a91CWPkTn0ImNSmDfwJqm2zMtmh9I6yf0drhp6CGPQMoBnX2wtbNBQzyiLFF8pLdtvJpEl5g04TKcXhakCZZ/yxUT4NKchurgEBMe/OHCpeldrWSY2TvAOTuIVyfhdqxdS+ru4AfR1zQ1IAZe6D0kTvKy3IQpctfFoGgWtUP9Aas8TDT6El3aR5lFpn8WQp77CCk1ZiZmdxJ68Fjc5YDinhxUzyZhwpTSSHzBqJhyx8PkJnS5rbtB5S1hs19MDaUm968+qKgGf6qzRVgY8HWDoeiuu9FSwnsXNauZSVUxIUR+8jQIqjXW75cWoY89mwhsR4b39TvG/r2N6t0jjKQrABv3S8tkQ2lebDBZezmga/B1ZXQplOK3VPbhGLbdgpantwp4cKO21vebUe7ox7jQAQfwQCwEsAEGIEQsWBgAAABAAAABwBgAAcAYAAAACAAAAAgBBrBELAZwAQbgRC4gBAQAAAIAAAAAqt+XjG0oXmT1fwfCx5O784AO9TgnUZVMR16JXmGN2v3o9mECCeDAAGug1UAMUQphdVh3+Egxi/i5+btn6Pm4dgxaM4a2z0XGSHPn9SFJMxSj6HZ1taBO9f5GkJKwrFChZi/iuNnthHF/nty14Yv5uZSXvnDW8lNnnEIjfthJAOwBBzBILASwAQdgSCxUGAAAAEAAAAMAIAADACAAAgAAAAIAAQfwSCwIcAgBBiBMLhQQBAAAAAAIAAI8BAADOAAAAzwAAAK8AAADDAAAAtAEAAAMAAADoAAAAOAAAAMABAADNAAAAdwEAAPcAAACcAAAAHwEAAOAAAABVAQAAhgEAAKQBAABRAAAALAAAAF4BAAD1AQAAvgEAAJEAAACzAQAAoAAAACUBAACbAAAA5AEAAAkAAADXAAAAcgEAACQAAACAAAAAtwEAAJIBAAB6AAAA2gAAAHYAAADZAAAAhwEAAJYBAAAmAAAAigAAAKUAAADAAAAAeAAAACgBAADhAQAAjQAAAKcAAAB5AAAAKgAAAGsBAADRAAAAqgEAAJ4BAADrAAAA7QEAAEMBAAAIAAAAmwEAAM4BAACeAAAADwAAAL0BAABlAQAAlwEAAHsAAABWAQAASgEAAJoBAABiAAAA+gEAAAEAAABtAQAAVgAAAOkAAAAMAQAAIwEAAL8BAABpAAAALwEAAG8BAAA8AAAA7gEAAE0AAADeAAAA8gEAAIcAAAAxAAAA0gAAAIsBAADiAQAAiAEAAGAAAADGAQAAbwAAANUBAAD0AAAALgAAABkBAAAmAQAA3AAAAAMBAAAzAAAA8wAAANoBAAA1AQAADQAAAGQBAABrAAAAcwAAADwBAADqAAAAygEAAGwAAAApAAAAbQAAAAsBAAAxAQAAkQEAAPEAAAAqAQAAGQAAAH0BAAA7AEGcFwsBLABBqBcLFQcAAAAQAAAAkAkAAJAJAAAAAgAAgABBzBcLAhwBAEHYFwuIAgEAAAAAAQAAmC+KQpFEN3HP+8C1pdu16VvCVjnxEfFZpII/ktVeHKuYqgfYAVuDEr6FMSTDfQxVdF2+cv6x3oCnBtybdPGbwcFpm+SGR77vxp3BD8yhDCRvLOktqoR0StypsFzaiPl2UlE+mG3GMajIJwOwx39Zv/ML4MZHkafVUWPKBmcpKRSFCrcnOCEbLvxtLE0TDThTVHMKZbsKanYuycKBhSxykqHov6JLZhqocItLwqNRbMcZ6JLRJAaZ1oU1DvRwoGoQFsGkGQhsNx5Md0gntbywNLMMHDlKqthOT8qcW/NvLmjugo90b2OleBR4yIQIAseM+v++kOtsUKT3o/m+8nhxxgBB7BkLASwAQfgZCxUIAAAAEAAAAOALAADgCwAAAAEAAEAAQZwaCwIcAQBBqBoLiAIBAAAAAAEAAGN8d3vya2/FMAFnK/7Xq3bKgsl9+llH8K3Uoq+cpHLAt/2TJjY/98w0peXxcdgxFQTHI8MYlgWaBxKA4usnsnUJgywaG25aoFI71rMp4y+EU9EA7SD8sVtqy745SkxYz9DvqvtDTTOFRfkCf1A8n6hRo0CPkp049by22iEQ//PSzQwT7F+XRBfEp349ZF0Zc2CBT9wiKpCIRu64FN5eC9vgMjoKSQYkXMLTrGKRleR558g3bY3VTqlsVvTqZXquCLp4JS4cprTG6N10H0u9i4pwPrVmSAP2DmE1V7mGwR2e4fiYEWnZjpSbHofpzlUo34yhiQ2/5kJoQZktD7BUuxYAQbwcCwEsAEHIHAsWBgAAABAAAAAwDQAAMA0AAAABAAAAAQBB7BwLARwAQfgcCxMBAAAACwAAAAABAgQIECBAgBs2AEGMHQsBLABBmB0LFQYAAAAQAAAAgA4AAIAOAAALAAAACwBBvB0LASwAQcgdCyECAAAAGgAAAH4AbABpAGIALwBhAHIAcgBhAHkALgB0AHMAQewdCwEcAEH4HQsBAQBBjB4LATwAQZgeCysCAAAAJAAAAH4AbABpAGIALwB0AHkAcABlAGQAYQByAHIAYQB5AC4AdABzAEHMHgsBPABB2B4LMQIAAAAqAAAAdgBpAGQAdQBrAGkAOgB3AHIAYQBwAC0AcABlAHAAcABlAHIAOgB2ADEAQYwfCwE8AEGYHwstAgAAACYAAAB+AGwAaQBiAC8AcwB0AGEAdABpAGMAYQByAHIAYQB5AC4AdABzAEHMHwsBLABB2B8LIwIAAAAcAAAAdgBpAGQAdQBrAGkAOgB3AHIAYQBwADoAdgAxAEGAIAsqCgAAACAAAAAgAAAAIAAAAAAAAABBAAAAAkEAAEIAAAACCQAAAgEAACQB"), c => c.charCodeAt(0)).buffer;

const API_BASE = "https://api.viduki.net";
const ORIGIN = "https://www.viduki.net";
const BROWSER_HEADERS = {
  "User-Agent": "Mozilla/5.0 (Cloudflare Worker) AppleWebKit/537.36 Chrome/137 Safari/537.36",
  Origin: ORIGIN,
  Referer: `${ORIGIN}/`,
  "Accept-Language": "en-US,en;q=0.9",
};

function json(data, status = 200, extra = {}) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", ...extra },
  });
}

function cors(request, response) {
  const origin = request.headers.get("Origin");
  const allowed = origin || "*";
  const headers = new Headers(response.headers);
  headers.set("Access-Control-Allow-Origin", allowed);
  headers.set("Access-Control-Allow-Headers", "content-type, authorization");
  headers.set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  headers.set("Vary", "Origin");
  return new Response(response.body, { status: response.status, headers });
}

function hexBytes(value, name) {
  if (typeof value !== "string" || value.length % 2 || !/^[0-9a-f]+$/i.test(value)) throw new Error(`invalid hex field: ${name}`);
  const out = new Uint8Array(value.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(value.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function int64be(value) {
  const out = new Uint8Array(8);
  new DataView(out.buffer).setBigInt64(0, BigInt(value), false);
  return out;
}

async function sha256Hex(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map(x => x.toString(16).padStart(2, "0")).join("");
}

async function solveAltcha(challenge) {
  const target = String(challenge.challenge).toLowerCase();
  const salt = String(challenge.salt);
  const max = Number(challenge.maxnumber ?? 50000);
  for (let number = 0; number <= max; number++) {
    if (await sha256Hex(salt + String(number)) === target) {
      const took = 0;
      const payload = { algorithm: challenge.algorithm, challenge: challenge.challenge, number, salt, signature: challenge.signature, took };
      return btoa(JSON.stringify(payload));
    }
  }
  throw new Error("Altcha solution not found");
}

async function upstream(path, options = {}) {
  const response = await fetch(API_BASE + path, {
    ...options,
    headers: { ...BROWSER_HEADERS, Accept: "application/json", ...(options.headers || {}) },
  });
  const text = await response.text();
  let data;
  try { data = JSON.parse(text); } catch { throw new Error(`upstream ${path} returned non-JSON (${response.status})`); }
  if (!response.ok) throw new Error(`upstream ${path} failed (${response.status})`);
  return data;
}

async function getNonce() {
  const challenge = await upstream("/altcha-challenge");
  const solution = await solveAltcha(challenge);
  const result = await upstream("/bootstrap", { headers: { "X-Altcha": solution } });
  if (!result?.n || !/^[0-9a-f]{32}$/i.test(result.n)) throw new Error("invalid bootstrap nonce");
  return result.n;
}

function createCrypto() {
  let instance;
  const ready = WebAssembly.instantiate(WASM, { env: { abort() { throw new Error("WASM abort"); } } }).then(x => { instance = x.instance; return instance.exports; });
  const manifest = { alloc: "_gGry", reset: "_kuez", writeByte: "_0SGL", readByte: "_4vLu", decryptPepper: "_iUeM", decryptEnvelope: "_kGtw" };
  const put = (e, data) => { const ptr = e[manifest.alloc](data.length); data.forEach((v, i) => e[manifest.writeByte](ptr, i, v)); return { ptr, len: data.length }; };
  const read = (e, ptr, len) => { const out = new Uint8Array(len); for (let i = 0; i < len; i++) out[i] = e[manifest.readByte](ptr, i); return out; };
  return {
    async decryptPepper(envelope, nonce) {
      const e = await ready; e[manifest.reset]();
      const a = put(e, hexBytes(nonce, "nonce"));
      const b = put(e, int64be(envelope.bucket));
      const c = put(e, hexBytes(envelope.iv, "iv"));
      const d = put(e, hexBytes(envelope.ct, "ct"));
      const f = put(e, hexBytes(envelope.tag, "tag"));
      const result = e[manifest.decryptPepper](a.ptr, a.len, b.ptr, b.len, c.ptr, c.len, d.ptr, d.len, f.ptr, f.len);
      return e[manifest.readByte](result, 0) === 0;
    },
    async decryptEnvelope(envelope, fields) {
      const e = await ready;
      const a = put(e, hexBytes(fields.clientNonce, "clientNonce"));
      const b = put(e, hexBytes(envelope.sn, "serverNonce"));
      const tb = put(e, int64be(envelope.tb));
      const d = put(e, hexBytes(fields.requestId, "requestId"));
      const e2 = put(e, hexBytes(envelope.iv2, "iv2"));
      const f = put(e, hexBytes(envelope.wk, "wk"));
      const g = put(e, hexBytes(envelope.tag2, "tag2"));
      const h = put(e, hexBytes(envelope.iv1, "iv1"));
      const i = put(e, hexBytes(envelope.ct, "ct"));
      const j = put(e, hexBytes(envelope.tag1, "tag1"));
      const out = e[manifest.alloc](hexBytes(envelope.ct, "ct").length);
      const length = e[manifest.decryptEnvelope](a.ptr, a.len, b.ptr, b.len, tb.ptr, 8, d.ptr, d.len, e2.ptr, e2.len, f.ptr, f.len, g.ptr, g.len, h.ptr, h.len, i.ptr, i.len, j.ptr, j.len, out);
      return length > 0 ? read(e, out, length) : null;
    },
  };
}

function sourcePath(input, server) {
  const id = encodeURIComponent(String(input.tmdb_id));
  const srv = encodeURIComponent(server);
  if (input.type === "tv") return `/main/tv/${id}/${encodeURIComponent(String(input.season))}/${encodeURIComponent(String(input.episode))}?srv=${srv}`;
  return `/main/movie/${id}?srv=${srv}`;
}

function findUrl(value) {
  if (!value || typeof value !== "object") return null;
  if (typeof value.url === "string" && /^https?:\/\//i.test(value.url)) return value.url;
  for (const child of Object.values(value)) { const found = findUrl(child); if (found) return found; }
  return null;
}

async function getServers() {
  const data = await upstream("/main/servers");
  return Array.isArray(data) ? data : (Array.isArray(data?.servers) ? data.servers : (data?.data || []));
}

async function resolveAll(input) {
  const servers = await getServers();
  const nonce = await getNonce();
  const cryptoBox = createCrypto();
  const pepperChallenge = await upstream("/altcha-challenge");
  const pepperSolution = await solveAltcha(pepperChallenge);
  const pepper = await upstream("/pepper-key", { headers: { "X-Nonce": nonce, "X-Altcha": pepperSolution } });
  if (!await cryptoBox.decryptPepper(pepper, nonce)) throw new Error("pepper decrypt failed");

  const results = [];
  for (let offset = 0; offset < servers.length; offset += 3) {
    const batch = servers.slice(offset, offset + 3);
    const rows = await Promise.all(batch.map(async item => {
      const server = typeof item === "string" ? item : item.name;
      const clientNonce = [...crypto.getRandomValues(new Uint8Array(16))].map(x => x.toString(16).padStart(2, "0")).join("");
      const requestId = [...crypto.getRandomValues(new Uint8Array(16))].map(x => x.toString(16).padStart(2, "0")).join("");
      try {
        const envelope = await upstream(sourcePath(input, server), { headers: { "X-Nonce": nonce, "X-Client-Nonce": clientNonce, "X-Request-Id": requestId } });
        const clear = await cryptoBox.decryptEnvelope(envelope, { clientNonce, requestId });
        if (!clear) throw new Error("response decrypt failed");
        const data = JSON.parse(new TextDecoder().decode(clear));
        return { server, ok: true, stream_url: findUrl(data) };
      } catch (error) { return { server, ok: false, error: error.message }; }
    }));
    results.push(...rows);
  }
  return { ok: true, servers, success_count: results.filter(x => x.ok && x.stream_url).length, results };
}

function validInput(input) {
  if (!input || !["movie", "tv"].includes(input.type) || !Number.isInteger(Number(input.tmdb_id)) || Number(input.tmdb_id) <= 0) return false;
  if (input.type === "tv" && (!Number.isInteger(Number(input.season)) || !Number.isInteger(Number(input.episode)) || Number(input.season) < 1 || Number(input.episode) < 1)) return false;
  return true;
}

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") return cors(request, json({ ok: true }));
    const url = new URL(request.url);
    if (env.API_TOKEN && request.headers.get("Authorization") !== `Bearer ${env.API_TOKEN}`) return cors(request, json({ ok: false, error: "unauthorized" }, 401));
    try {
      if (request.method === "GET" && url.pathname === "/health") return cors(request, json({ ok: true, wasm: true }));
      if (request.method === "GET" && url.pathname === "/servers") return cors(request, json({ ok: true, servers: await getServers() }));
      if (request.method === "POST" && url.pathname === "/resolve-all") {
        const input = await request.json();
        if (!validInput(input)) return cors(request, json({ ok: false, error: "type, tmdb_id, season and episode are invalid" }, 400));
        return cors(request, json(await resolveAll(input)));
      }
      return cors(request, json({ ok: false, error: "not_found" }, 404));
    } catch (error) { return cors(request, json({ ok: false, error: error.message }, 502)); }
  },
};
